export const images = [
  {
    src: "/GW620.avif",
    alt: "Grow Waco",
    id: "1",
    category: "Community",
    uri: "https://growwaco.org",
  },
  {
    src: "/cake620.avif",
    alt: "Cake Amor",
    id: "2",
    category: "E-Commerce",
    uri: "https://cakeamor17.web.app/",
  },
  {
    src: "/Fabian620.avif",
    alt: "Project Fabian",
    id: "3",
    category: "Messaging",
    uri: "https://res.cloudinary.com/duysbh0j0/video/upload/v1724698473/FabisClip_o7xtfk.mp4",
  },
  {
    src: "/Fruit620.avif",
    alt: "Fruit Hoopz",
    id: "4",
    category: "Meet-ups",
    uri: "https://res.cloudinary.com/duysbh0j0/video/upload/v1719598943/fruit1_cclneu.mp4",
  },
  {
    src: "/Graphics620.avif",
    alt: "Designs/Logos",
    id: "5",
    category: "Graphics",
    uri: "https://www.linkedin.com/in/john-fabiszewski-00b8322a9",
  },
  {
    src: "/Lanther620.avif",
    alt: "Mission Lanther",
    id: "6",
    category: "Organizational",
    uri: "https://res.cloudinary.com/duysbh0j0/video/upload/v1719598953/lanther12_bna4df.mp4",
  },
  {
    src: "/Mueschke620.avif",
    alt: "Mueschke League",
    id: "7",
    category: "Informative",
    uri: "https://res.cloudinary.com/duysbh0j0/video/upload/v1719598962/mueschke1_xoutoh.mp4",
  },
  {
    src: "/RM620.avif",
    alt: "Political BLOG",
    id: "8",
    category: "BLOG",
    uri: "https://radical-middle.onrender.com/",
  },
  {
    src: "/Teresita620.avif",
    alt: "Teresita's Birria",
    id: "9",
    category: "Advertising",
    uri: "https://teresitas-birria.web.app/",
  },
  {
    src: "/Weirdos620.avif",
    alt: "Weirdo's BBQ",
    id: "10",
    category: "Advertising",
    uri: "https://weirdos-mikes-bbq.web.app/",
  },
  {
    src: "/Fresh620.avif",
    alt: "Fresh Notes",
    id: "11",
    category: "Notes",
    uri: "https://res.cloudinary.com/duysbh0j0/video/upload/v1724698477/FreshNotes_foubjj.mp4",
  },
  {
    src: "/MH620.avif",
    alt: "Band Archival",
    id: "12",
    category: "Historical",
    uri: "https://mirrahousehistory.firebaseapp.com/",
  },
];
